%.dis: %.b cmd.m
	limbo -g $stem.b

DIS=\
	t1.dis\
	t2.dis\


all: $DIS cmd.m
	./prep.sh test
	mash t1 p1 p3
	mash t2 p1 p3

test: $DIS
	./sort.sh
	mash run -x mashfile

clean:
	rm *.sbl *.out

nuke:
	rm -f *.sbl *.dis *.out
